apiVersion: yobitel.org/v1alpha1
kind: OperatorService
metadata:
  name: example-operatorservice
spec:
  # Default values copied from <project_dir>/helm-charts/postgresql/values.yaml
  
  hpa:
    enabled: true
  image: postgres
  imageTag: "12.3"
  metrics:
    enabled: false
    image: wrouesnel/postgres_exporter
    imagePullPolicy: IfNotPresent
    imageTag: v0.1.1
    resources:
      requests:
        cpu: 100m
        memory: 256Mi
  namespace: postgres
  networkPolicy:
    allowExternal: true
    enabled: false
  nodeSelector: {}
  persistence:
    accessMode: ReadWriteOnce
    enabled: true
    size: 8Gi
    subPath: postgresql-db
  podDisruptionBudget:
    maxUnavailable: 1
  podDisruptionBudgetEnabled: true
  resources:
    limits:
      cpu: 100m
      memory: 256Mi
    requests:
      cpu: 100m
      memory: 256Mi
  service:
    externalIPs: []
    port: 5432
    type: ClusterIP
  tolerations: []
  
